name = "Zeno"
license = "MIT"

licenselink = "https://raw.githubusercontent.com/lsenta/hugo-theme-explo/master/LICENSE.md"
description = "Zeno is a clean and simple theme for Zen Products, originally designed by @lsenta / @laurentsenta"

homepage = "https://github.com/lsenta/hugo-theme-zeno"

tags = ["landing", "blog", "light", "green", "lsenta", "singulargarden"]

#features = ["blog", "disqus", "google analytics", "pagination", "rss", "sharing options"]
#min_version = 0.14

[taxonomies]
tag = "tags"

